-- MySQL Script generated by MySQL Workbench
-- Sun Sep 13 15:18:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafedb_rm_edition
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Schema cafedb_rm_edition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafedb_rm_edition` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`GenericData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`GenericData` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`GenericData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `key` VARCHAR(45) NULL,
  `value` VARCHAR(255) NULL,
  `TestCase_Step_id` INT NOT NULL,
  `TestCase_Step_TestCase_id` INT NOT NULL,
  `TestCase_Step_Step_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Data_TestCase_Step1_idx` (`TestCase_Step_id` ASC, `TestCase_Step_TestCase_id` ASC, `TestCase_Step_Step_id` ASC) VISIBLE,
  CONSTRAINT `fk_Data_TestCase_Step1`
    FOREIGN KEY (`TestCase_Step_id` , `TestCase_Step_TestCase_id` , `TestCase_Step_Step_id`)
    REFERENCES `cafedb_rm_edition`.`TestCase_Step` (`id` , `TestCase_id` , `Step_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Login` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`ResultType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`ResultType` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`ResultType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Run`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Run` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Run` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `startTime` TIMESTAMP NOT NULL,
  `endTime` TIMESTAMP NULL,
  `scriptVersion` INT NOT NULL,
  `softwareVersion` VARCHAR(45) NOT NULL,
  `ResultType_id` INT NOT NULL,
  `TestCase_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Run_ResultType1_idx` (`ResultType_id` ASC) VISIBLE,
  INDEX `fk_Run_TestCase1_idx` (`TestCase_id` ASC) VISIBLE,
  CONSTRAINT `fk_Run_ResultType1`
    FOREIGN KEY (`ResultType_id`)
    REFERENCES `cafedb_rm_edition`.`ResultType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_TestCase1`
    FOREIGN KEY (`TestCase_id`)
    REFERENCES `cafedb_rm_edition`.`TestCase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Step` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Step` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `function` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`StepResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`StepResult` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`StepResult` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `resulttext` VARCHAR(255) NOT NULL,
  `imagepath` VARCHAR(45) NULL,
  `ResultType_id` INT NOT NULL,
  `Run_id` INT NOT NULL,
  `Step_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_StepResult_ResultType1_idx` (`ResultType_id` ASC) VISIBLE,
  INDEX `fk_StepResult_Run1_idx` (`Run_id` ASC) VISIBLE,
  INDEX `fk_StepResult_Step1_idx` (`Step_id` ASC) VISIBLE,
  CONSTRAINT `fk_StepResult_ResultType1`
    FOREIGN KEY (`ResultType_id`)
    REFERENCES `cafedb_rm_edition`.`ResultType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StepResult_Run1`
    FOREIGN KEY (`Run_id`)
    REFERENCES `cafedb_rm_edition`.`Run` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StepResult_Step1`
    FOREIGN KEY (`Step_id`)
    REFERENCES `cafedb_rm_edition`.`Step` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Suite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Suite` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Suite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestCase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestCase` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestCase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(255) NOT NULL,
  `scriptVersion` INT NOT NULL,
  `testRailId` INT NOT NULL,
  `TestType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TestCase_TestType1_idx` (`TestType_id` ASC) VISIBLE,
  CONSTRAINT `fk_TestCase_TestType1`
    FOREIGN KEY (`TestType_id`)
    REFERENCES `cafedb_rm_edition`.`TestType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestCase_Step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestCase_Step` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestCase_Step` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `TestCase_id` INT NOT NULL,
  `Step_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TestCase_id`, `Step_id`),
  INDEX `fk_Case_Step_TestCase1_idx` (`TestCase_id` ASC) VISIBLE,
  INDEX `fk_Case_Step_Step1_idx` (`Step_id` ASC) VISIBLE,
  CONSTRAINT `fk_Case_Step_TestCase1`
    FOREIGN KEY (`TestCase_id`)
    REFERENCES `cafedb_rm_edition`.`TestCase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_Step_Step1`
    FOREIGN KEY (`Step_id`)
    REFERENCES `cafedb_rm_edition`.`Step` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestCase_Suite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestCase_Suite` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestCase_Suite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `Suite_id` INT NOT NULL,
  `TestCase_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Suite_id`, `TestCase_id`),
  INDEX `fk_Driver_Suite_Suite1_idx` (`Suite_id` ASC) VISIBLE,
  INDEX `fk_Case_Suite_TestCase1_idx` (`TestCase_id` ASC) VISIBLE,
  CONSTRAINT `fk_Driver_Suite_Suite1`
    FOREIGN KEY (`Suite_id`)
    REFERENCES `cafedb_rm_edition`.`Suite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_Suite_TestCase1`
    FOREIGN KEY (`TestCase_id`)
    REFERENCES `cafedb_rm_edition`.`TestCase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestType` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));

USE `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Placeholder table for view `cafedb_rm_edition`.`overView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`overView` (`id` INT, `TestCaseName` INT, `scriptVersion` INT, `testRailId` INT, `TestType` INT, `Suite` INT, `SuiteDescription` INT);

-- -----------------------------------------------------
-- Placeholder table for view `cafedb_rm_edition`.`steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`steps` (`Step` INT, `function` INT, `TestCase` INT, `Key` INT, `Value` INT);

-- -----------------------------------------------------
-- Placeholder table for view `cafedb_rm_edition`.`runs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`runs` (`name` INT, `startTime` INT, `endTime` INT, `scriptVersion` INT, `softwareVersion` INT, `ResultType` INT);

-- -----------------------------------------------------
-- View `cafedb_rm_edition`.`overView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`overView`;
DROP VIEW IF EXISTS `cafedb_rm_edition`.`overView` ;
USE `cafedb_rm_edition`;
CREATE  OR REPLACE VIEW `overView` AS
SELECT tc.id, tc.name TestCaseName, tc.scriptVersion, tc.testRailId, tt.Name TestType, s.Name Suite, s.Description SuiteDescription
FROM TestCase tc
INNER JOIN TestType tt ON tt.id = tc.TestType_id
INNER JOIN TestCase_Suite tcs ON tc.id = tcs.TestCase_id 
INNER JOIN Suite s ON  s.id = tcs.Suite_id;

-- -----------------------------------------------------
-- View `cafedb_rm_edition`.`steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`steps`;
DROP VIEW IF EXISTS `cafedb_rm_edition`.`steps` ;
USE `cafedb_rm_edition`;
CREATE  OR REPLACE VIEW `steps` AS
SELECT s.name Step, s.function, tc.name TestCase, gd.Key, gd.Value
FROM Step s
INNER JOIN TestCase_Step tcs ON tcs.Step_id = s.id
INNER JOIN TestCase tc ON tc.id = tcs.TestCase_id
INNER JOIN GenericData gd ON gd.TestCase_Step_id = tcs.id;

-- -----------------------------------------------------
-- View `cafedb_rm_edition`.`runs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`runs`;
DROP VIEW IF EXISTS `cafedb_rm_edition`.`runs` ;
USE `cafedb_rm_edition`;
CREATE  OR REPLACE VIEW `runs` AS
    SELECT 
        tc.name,
        r.startTime,
        r.endTime,
        r.scriptVersion,
        r.softwareVersion,
        rt.name ResultType
    FROM
        Run r
            INNER JOIN
        TestCase tc ON r.TestCase_id = tc.id
            INNER JOIN
        ResultType rt ON r.ResultType_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `cafedb_rm_edition`;

DELIMITER $$

USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`GenericData_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`GenericData_BEFORE_UPDATE` BEFORE UPDATE ON `GenericData` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Login_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Login_BEFORE_UPDATE` BEFORE UPDATE ON `Login` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`ResultType_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`ResultType_BEFORE_UPDATE` BEFORE UPDATE ON `ResultType` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Run_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Run_BEFORE_UPDATE` BEFORE UPDATE ON `Run` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Step_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Step_BEFORE_UPDATE` BEFORE UPDATE ON `Step` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`StepResult_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`StepResult_BEFORE_UPDATE` BEFORE UPDATE ON `StepResult` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Suite_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Suite_BEFORE_UPDATE` BEFORE UPDATE ON `Suite` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestCase_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestCase_BEFORE_UPDATE` BEFORE UPDATE ON `TestCase` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestCase_Step_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestCase_Step_BEFORE_UPDATE` BEFORE UPDATE ON `TestCase_Step` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestCase_Suite_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestCase_Suite_BEFORE_UPDATE` BEFORE UPDATE ON `TestCase_Suite` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestType_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestType_BEFORE_UPDATE` BEFORE UPDATE ON `TestType` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


DELIMITER ;
