-- MySQL Script generated by MySQL Workbench
-- Sat Sep 12 23:16:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafedb_rm_edition
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Schema cafedb_rm_edition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafedb_rm_edition` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`BusinessFlow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`BusinessFlow` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`BusinessFlow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `function` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Driver` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(255) NOT NULL,
  `scriptVersion` INT NOT NULL,
  `testRailId` INT NOT NULL,
  `TestType_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TestType_id`),
  INDEX `fk_Driver_TestType1_idx` (`TestType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Driver_TestType1`
    FOREIGN KEY (`TestType_id`)
    REFERENCES `cafedb_rm_edition`.`TestType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Driver_BusinessFlow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Driver_BusinessFlow` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Driver_BusinessFlow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `Driver_id` INT NOT NULL,
  `BusinessFlow_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Driver_id`, `BusinessFlow_id`),
  INDEX `fk_Driver_BusinessFlow_Driver_idx` (`Driver_id` ASC) VISIBLE,
  INDEX `fk_Driver_BusinessFlow_BusinessFlow1_idx` (`BusinessFlow_id` ASC) VISIBLE,
  CONSTRAINT `fk_Driver_BusinessFlow_Driver`
    FOREIGN KEY (`Driver_id`)
    REFERENCES `cafedb_rm_edition`.`Driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Driver_BusinessFlow_BusinessFlow1`
    FOREIGN KEY (`BusinessFlow_id`)
    REFERENCES `cafedb_rm_edition`.`BusinessFlow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Driver_Suite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Driver_Suite` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Driver_Suite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `Driver_id` INT NOT NULL,
  `Driver_TestType_id` INT NOT NULL,
  `Suite_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Driver_id`, `Driver_TestType_id`, `Suite_id`),
  INDEX `fk_Driver_Suite_Driver1_idx` (`Driver_id` ASC, `Driver_TestType_id` ASC) VISIBLE,
  INDEX `fk_Driver_Suite_Suite1_idx` (`Suite_id` ASC) VISIBLE,
  CONSTRAINT `fk_Driver_Suite_Driver1`
    FOREIGN KEY (`Driver_id` , `Driver_TestType_id`)
    REFERENCES `cafedb_rm_edition`.`Driver` (`id` , `TestType_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Driver_Suite_Suite1`
    FOREIGN KEY (`Suite_id`)
    REFERENCES `cafedb_rm_edition`.`Suite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`GenericData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`GenericData` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`GenericData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `key` VARCHAR(45) NULL,
  `value` VARCHAR(255) NULL,
  `Driver_BusinessFlow_id` INT NOT NULL,
  `Driver_BusinessFlow_Driver_id` INT NOT NULL,
  `Driver_BusinessFlow_BusinessFlow_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_GenericData_Driver_BusinessFlow1_idx` (`Driver_BusinessFlow_id` ASC, `Driver_BusinessFlow_Driver_id` ASC, `Driver_BusinessFlow_BusinessFlow_id` ASC) VISIBLE,
  CONSTRAINT `fk_GenericData_Driver_BusinessFlow1`
    FOREIGN KEY (`Driver_BusinessFlow_id` , `Driver_BusinessFlow_Driver_id` , `Driver_BusinessFlow_BusinessFlow_id`)
    REFERENCES `cafedb_rm_edition`.`Driver_BusinessFlow` (`id` , `Driver_id` , `BusinessFlow_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`ResultType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`ResultType` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`ResultType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Run`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Run` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Run` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `startTime` TIMESTAMP NOT NULL,
  `endTime` TIMESTAMP NULL,
  `scriptVersion` INT NOT NULL,
  `softwareVersion` VARCHAR(45) NOT NULL,
  `ResultType_id` INT NOT NULL,
  `Driver_id` INT NOT NULL,
  `Driver_TestType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Run_ResultType1_idx` (`ResultType_id` ASC) VISIBLE,
  INDEX `fk_Run_Driver1_idx` (`Driver_id` ASC, `Driver_TestType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Run_ResultType1`
    FOREIGN KEY (`ResultType_id`)
    REFERENCES `cafedb_rm_edition`.`ResultType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_Driver1`
    FOREIGN KEY (`Driver_id` , `Driver_TestType_id`)
    REFERENCES `cafedb_rm_edition`.`Driver` (`id` , `TestType_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`StepResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`StepResult` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`StepResult` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `resulttext` VARCHAR(255) NOT NULL,
  `imagepath` VARCHAR(45) NULL,
  `ResultType_id` INT NOT NULL,
  `BusinessFlow_id` INT NOT NULL,
  `Run_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_StepResult_ResultType1_idx` (`ResultType_id` ASC) VISIBLE,
  INDEX `fk_StepResult_BusinessFlow1_idx` (`BusinessFlow_id` ASC) VISIBLE,
  INDEX `fk_StepResult_Run1_idx` (`Run_id` ASC) VISIBLE,
  CONSTRAINT `fk_StepResult_ResultType1`
    FOREIGN KEY (`ResultType_id`)
    REFERENCES `cafedb_rm_edition`.`ResultType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StepResult_BusinessFlow1`
    FOREIGN KEY (`BusinessFlow_id`)
    REFERENCES `cafedb_rm_edition`.`BusinessFlow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StepResult_Run1`
    FOREIGN KEY (`Run_id`)
    REFERENCES `cafedb_rm_edition`.`Run` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Suite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Suite` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Suite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestType` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));

USE `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Placeholder table for view `cafedb_rm_edition`.`overView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`overView` (`id` INT, `name` INT, `scriptVersion` INT, `testRailId` INT, `TestType_name` INT, `Suite_name` INT, `description` INT);

-- -----------------------------------------------------
-- Placeholder table for view `cafedb_rm_edition`.`businessFlowView`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`businessFlowView` (`BusinessFlow_name` INT, `function` INT, `Driver_name` INT, `Key` INT, `Value` INT);

-- -----------------------------------------------------
-- Placeholder table for view `cafedb_rm_edition`.`getRun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`getRun` (`Driver_name` INT, `startTime` INT, `endTime` INT, `scriptVersion` INT, `softwareVersion` INT, `ResultType_name` INT);

-- -----------------------------------------------------
-- View `cafedb_rm_edition`.`overView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`overView`;
DROP VIEW IF EXISTS `cafedb_rm_edition`.`overView` ;
USE `cafedb_rm_edition`;
CREATE  OR REPLACE VIEW `overView` AS
SELECT d.id, d.name, d.scriptVersion, d.testRailId, tt.name TestType_name, s.name Suite_name, s.description
FROM driver d
INNER JOIN TestType tt ON tt.id = d.TestType_id
INNER JOIN Driver_Suite ds ON d.id = ds.Driver_id 
INNER JOIN Suite s ON  s.id = ds.Suite_id;

-- -----------------------------------------------------
-- View `cafedb_rm_edition`.`businessFlowView`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`businessFlowView`;
DROP VIEW IF EXISTS `cafedb_rm_edition`.`businessFlowView` ;
USE `cafedb_rm_edition`;
CREATE  OR REPLACE VIEW `businessFlowView` AS
SELECT b.name BusinessFlow_name, b.function, d.name Driver_name, gd.Key, gd.Value
FROM BusinessFlow b
INNER JOIN Driver_BusinessFlow db ON db.BusinessFlow_id = b.Id
INNER JOIN Driver d ON d.id = db.Driver_id
INNER JOIN GenericData gd ON gd.Driver_BusinessFlow_BusinessFlow_id = db.BusinessFlow_id;

-- -----------------------------------------------------
-- View `cafedb_rm_edition`.`getRun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`getRun`;
DROP VIEW IF EXISTS `cafedb_rm_edition`.`getRun` ;
USE `cafedb_rm_edition`;
CREATE  OR REPLACE VIEW `getRun` AS
    SELECT 
        d.name Driver_name,
        r.startTime,
        r.endTime,
        r.scriptVersion,
        r.softwareVersion,
        rt.name ResultType_name
    FROM
        Run r
            INNER JOIN
        Driver d ON r.Driver_id = d.id
            INNER JOIN
        ResultType rt ON r.ResultType_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `cafedb_rm_edition`;

DELIMITER $$

USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`BusinessFlow_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`BusinessFlow_BEFORE_UPDATE` BEFORE UPDATE ON `BusinessFlow` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Driver_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Driver_BEFORE_UPDATE` BEFORE UPDATE ON `Driver` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Driver_BusinessFlow_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Driver_BusinessFlow_BEFORE_UPDATE` BEFORE UPDATE ON `Driver_BusinessFlow` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Driver_Suite_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Driver_Suite_BEFORE_UPDATE` BEFORE UPDATE ON `Driver_Suite` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`GenericData_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`GenericData_BEFORE_UPDATE` BEFORE UPDATE ON `GenericData` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`ResultType_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`ResultType_BEFORE_UPDATE` BEFORE UPDATE ON `ResultType` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Run_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Run_BEFORE_UPDATE` BEFORE UPDATE ON `Run` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`StepResult_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`StepResult_BEFORE_UPDATE` BEFORE UPDATE ON `StepResult` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Suite_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Suite_BEFORE_UPDATE` BEFORE UPDATE ON `Suite` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestType_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestType_BEFORE_UPDATE` BEFORE UPDATE ON `TestType` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


DELIMITER ;
