-- MySQL Script generated by MySQL Workbench
-- Wed Sep 30 23:30:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafedb_rm_edition
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Schema cafedb_rm_edition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafedb_rm_edition` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cafedb_rm_edition` ;

-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Login` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `lastProduct` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Module` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `hidden` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Module_Step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Module_Step` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Module_Step` (
  `Module_id` INT NOT NULL,
  `Step_id` INT NOT NULL,
  `stepNumber` INT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`Module_id`, `Step_id`),
  INDEX `fk_Module_has_Step_Step1_idx` (`Step_id` ASC) VISIBLE,
  INDEX `fk_Module_has_Step_Module1_idx` (`Module_id` ASC) VISIBLE,
  CONSTRAINT `fk_Module_has_Step_Module1`
    FOREIGN KEY (`Module_id`)
    REFERENCES `cafedb_rm_edition`.`Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Module_has_Step_Step1`
    FOREIGN KEY (`Step_id`)
    REFERENCES `cafedb_rm_edition`.`Step` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Product` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`ResultType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`ResultType` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`ResultType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Run`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Run` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Run` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `endTime` TIMESTAMP NULL,
  `scriptVersion` INT NOT NULL,
  `softwareVersion` VARCHAR(45) NOT NULL,
  `Suite_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Suite_id`),
  INDEX `fk_Run_Suite1_idx` (`Suite_id` ASC) VISIBLE,
  CONSTRAINT `fk_Run_Suite1`
    FOREIGN KEY (`Suite_id`)
    REFERENCES `cafedb_rm_edition`.`Suite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Step`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Step` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Step` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `function` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`StepData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`StepData` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`StepData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `Step_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Step_id`),
  INDEX `fk_StepData_Step1_idx` (`Step_id` ASC) VISIBLE,
  CONSTRAINT `fk_StepData_Step1`
    FOREIGN KEY (`Step_id`)
    REFERENCES `cafedb_rm_edition`.`Step` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`StepResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`StepResult` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`StepResult` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `resulttext` VARCHAR(255) NOT NULL,
  `imagepath` VARCHAR(45) NULL,
  `ResultType_id` INT NOT NULL,
  `Step_id` INT NOT NULL,
  `TestResult_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Step_id`),
  INDEX `fk_StepResult_ResultType1_idx` (`ResultType_id` ASC) VISIBLE,
  INDEX `fk_StepResult_Step1_idx` (`Step_id` ASC) VISIBLE,
  INDEX `fk_StepResult_TestResult1_idx` (`TestResult_id` ASC) VISIBLE,
  CONSTRAINT `fk_StepResult_ResultType1`
    FOREIGN KEY (`ResultType_id`)
    REFERENCES `cafedb_rm_edition`.`ResultType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StepResult_Step1`
    FOREIGN KEY (`Step_id`)
    REFERENCES `cafedb_rm_edition`.`Step` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StepResult_TestResult1`
    FOREIGN KEY (`TestResult_id`)
    REFERENCES `cafedb_rm_edition`.`TestResult` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`Suite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`Suite` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`Suite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Product_id`),
  INDEX `fk_Suite_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Suite_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `cafedb_rm_edition`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestCase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestCase` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestCase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `scriptVersion` INT NOT NULL,
  `testRailId` INT NOT NULL,
  `TestType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TestCase_TestType1_idx` (`TestType_id` ASC) VISIBLE,
  CONSTRAINT `fk_TestCase_TestType1`
    FOREIGN KEY (`TestType_id`)
    REFERENCES `cafedb_rm_edition`.`TestType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestCase_Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestCase_Module` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestCase_Module` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `Module_id` INT NOT NULL,
  `TestCase_id` INT NOT NULL,
  `moduleNumber` INT NULL DEFAULT 0,
  PRIMARY KEY (`Module_id`, `TestCase_id`),
  INDEX `fk_TestCase_Module_TestCase1_idx` (`TestCase_id` ASC) VISIBLE,
  CONSTRAINT `fk_TestCase_Module_Module1`
    FOREIGN KEY (`Module_id`)
    REFERENCES `cafedb_rm_edition`.`Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TestCase_Module_TestCase1`
    FOREIGN KEY (`TestCase_id`)
    REFERENCES `cafedb_rm_edition`.`TestCase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestCase_Suite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestCase_Suite` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestCase_Suite` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `Suite_id` INT NOT NULL,
  `TestCase_id` INT NOT NULL,
  PRIMARY KEY (`Suite_id`, `TestCase_id`),
  INDEX `fk_Driver_Suite_Suite1_idx` (`Suite_id` ASC) VISIBLE,
  INDEX `fk_Case_Suite_TestCase1_idx` (`TestCase_id` ASC) VISIBLE,
  CONSTRAINT `fk_Driver_Suite_Suite1`
    FOREIGN KEY (`Suite_id`)
    REFERENCES `cafedb_rm_edition`.`Suite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_Suite_TestCase1`
    FOREIGN KEY (`TestCase_id`)
    REFERENCES `cafedb_rm_edition`.`TestCase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestResult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestResult` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestResult` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `ResultType_id` INT NOT NULL,
  `TestCase_id` INT NOT NULL,
  `Run_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TestCase_id`, `Run_id`),
  INDEX `fk_TestResult_ResultType1_idx` (`ResultType_id` ASC) VISIBLE,
  INDEX `fk_TestResult_TestCase1_idx` (`TestCase_id` ASC) VISIBLE,
  INDEX `fk_TestResult_Run1_idx` (`Run_id` ASC) VISIBLE,
  CONSTRAINT `fk_TestResult_ResultType1`
    FOREIGN KEY (`ResultType_id`)
    REFERENCES `cafedb_rm_edition`.`ResultType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TestResult_TestCase1`
    FOREIGN KEY (`TestCase_id`)
    REFERENCES `cafedb_rm_edition`.`TestCase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TestResult_Run1`
    FOREIGN KEY (`Run_id`)
    REFERENCES `cafedb_rm_edition`.`Run` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cafedb_rm_edition`.`TestType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cafedb_rm_edition`.`TestType` ;

CREATE TABLE IF NOT EXISTS `cafedb_rm_edition`.`TestType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));

USE `cafedb_rm_edition`;

DELIMITER $$

USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Login_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Login_BEFORE_UPDATE` BEFORE UPDATE ON `Login` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Module_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Module_BEFORE_UPDATE` BEFORE UPDATE ON `Module` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Module_Step_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Module_Step_BEFORE_UPDATE` BEFORE UPDATE ON `Module_Step` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Product_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Product_BEFORE_UPDATE` BEFORE UPDATE ON `Product` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`ResultType_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`ResultType_BEFORE_UPDATE` BEFORE UPDATE ON `ResultType` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Run_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Run_BEFORE_UPDATE` BEFORE UPDATE ON `Run` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Step_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Step_BEFORE_UPDATE` BEFORE UPDATE ON `Step` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`StepData_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`StepData_BEFORE_UPDATE` BEFORE UPDATE ON `StepData` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`StepResult_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`StepResult_BEFORE_UPDATE` BEFORE UPDATE ON `StepResult` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`Suite_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`Suite_BEFORE_UPDATE` BEFORE UPDATE ON `Suite` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestCase_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestCase_BEFORE_UPDATE` BEFORE UPDATE ON `TestCase` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestCase_Module_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestCase_Module_BEFORE_UPDATE` BEFORE UPDATE ON `TestCase_Module` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestCase_Suite_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestCase_Suite_BEFORE_UPDATE` BEFORE UPDATE ON `TestCase_Suite` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestResult_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestResult_BEFORE_UPDATE` BEFORE UPDATE ON `TestResult` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


USE `cafedb_rm_edition`$$
DROP TRIGGER IF EXISTS `cafedb_rm_edition`.`TestType_BEFORE_UPDATE` $$
USE `cafedb_rm_edition`$$
CREATE DEFINER = CURRENT_USER TRIGGER `cafedb_rm_edition`.`TestType_BEFORE_UPDATE` BEFORE UPDATE ON `TestType` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIMESTAMP; 
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cafedb_rm_edition`.`Login`
-- -----------------------------------------------------
START TRANSACTION;
USE `cafedb_rm_edition`;
INSERT INTO `cafedb_rm_edition`.`Login` (`id`, `create_time`, `update_time`, `name`, `password`, `lastProduct`) VALUES (DEFAULT, NULL, NULL, 'test', 't', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `cafedb_rm_edition`.`ResultType`
-- -----------------------------------------------------
START TRANSACTION;
USE `cafedb_rm_edition`;
INSERT INTO `cafedb_rm_edition`.`ResultType` (`id`, `create_time`, `update_time`, `name`) VALUES (DEFAULT, NULL, NULL, 'Passed');
INSERT INTO `cafedb_rm_edition`.`ResultType` (`id`, `create_time`, `update_time`, `name`) VALUES (DEFAULT, NULL, NULL, 'Failed');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cafedb_rm_edition`.`TestType`
-- -----------------------------------------------------
START TRANSACTION;
USE `cafedb_rm_edition`;
INSERT INTO `cafedb_rm_edition`.`TestType` (`id`, `create_time`, `update_time`, `name`) VALUES (DEFAULT, NULL, NULL, 'Not specified');
INSERT INTO `cafedb_rm_edition`.`TestType` (`id`, `create_time`, `update_time`, `name`) VALUES (DEFAULT, NULL, NULL, 'Regression');
INSERT INTO `cafedb_rm_edition`.`TestType` (`id`, `create_time`, `update_time`, `name`) VALUES (DEFAULT, NULL, NULL, 'Performance');

COMMIT;

